# syntax=docker/dockerfile:1
# Self-contained migration image: bakes goose + this repo's migrations
# together, versioned with the code instead of depending on an external
# registry image or a separately-maintained ConfigMap.

FROM golang:1.25-alpine AS build
RUN go install github.com/pressly/goose/v3/cmd/goose@v3.24.3

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
COPY --from=build /go/bin/goose /usr/local/bin/goose
COPY migrations /migrations
ENTRYPOINT ["goose", "-dir", "/migrations"]
