// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const categoryCreate = `-- name: CategoryCreate :one
INSERT INTO categories (user_id, name, icon_name, color_hex, type, is_default)
VALUES ($1, $2, $3, $4, $5, false)
RETURNING id, user_id, name, icon_name, color_hex, type, is_default, created_at
`

type CategoryCreateParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Name     string      `json:"name"`
	IconName string      `json:"icon_name"`
	ColorHex string      `json:"color_hex"`
	Type     string      `json:"type"`
}

func (q *Queries) CategoryCreate(ctx context.Context, arg CategoryCreateParams) (Category, error) {
	row := q.db.QueryRow(ctx, categoryCreate,
		arg.UserID,
		arg.Name,
		arg.IconName,
		arg.ColorHex,
		arg.Type,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IconName,
		&i.ColorHex,
		&i.Type,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const categoryDeleteForUser = `-- name: CategoryDeleteForUser :execrows
DELETE FROM categories
WHERE id = $1 AND user_id = $2 AND is_default = false
`

type CategoryDeleteForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Only deletes a category owned by the user; default categories can't be deleted this way.
func (q *Queries) CategoryDeleteForUser(ctx context.Context, arg CategoryDeleteForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, categoryDeleteForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const categoryGetByID = `-- name: CategoryGetByID :one
SELECT id, user_id, name, icon_name, color_hex, type, is_default, created_at
FROM categories
WHERE id = $1
`

func (q *Queries) CategoryGetByID(ctx context.Context, id pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, categoryGetByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IconName,
		&i.ColorHex,
		&i.Type,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const categoryListForUser = `-- name: CategoryListForUser :many
SELECT id, user_id, name, icon_name, color_hex, type, is_default, created_at
FROM categories
WHERE user_id = $1 OR is_default = true
ORDER BY is_default DESC, name
`

// Returns the user's own categories plus the shared default ones.
func (q *Queries) CategoryListForUser(ctx context.Context, userID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, categoryListForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.IconName,
			&i.ColorHex,
			&i.Type,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
