// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	IconName  string             `json:"icon_name"`
	ColorHex  string             `json:"color_hex"`
	Type      string             `json:"type"`
	IsDefault bool               `json:"is_default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ExchangeRate struct {
	Currency  string             `json:"currency"`
	RateToUah pgtype.Numeric     `json:"rate_to_uah"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	Amount     pgtype.Numeric     `json:"amount"`
	Currency   string             `json:"currency"`
	Type       string             `json:"type"`
	Date       pgtype.Timestamptz `json:"date"`
	Note       string             `json:"note"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	AppleSub     string             `json:"apple_sub"`
	Email        pgtype.Text        `json:"email"`
	BaseCurrency string             `json:"base_currency"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
