// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	IconName  string             `json:"icon_name"`
	ColorHex  string             `json:"color_hex"`
	Type      string             `json:"type"`
	IsDefault bool               `json:"is_default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	NameUk    pgtype.Text        `json:"name_uk"`
	NameEn    pgtype.Text        `json:"name_en"`
}

type MonobankConnection struct {
	UserID         pgtype.UUID        `json:"user_id"`
	EncryptedToken []byte             `json:"encrypted_token"`
	WebhookSecret  string             `json:"webhook_secret"`
	ConnectedAt    pgtype.Timestamptz `json:"connected_at"`
	LastSyncedAt   pgtype.Timestamptz `json:"last_synced_at"`
	AccountIds     []string           `json:"account_ids"`
	MaskedPans     []string           `json:"masked_pans"`
}

type PaymentEvent struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	OrderID          string             `json:"order_id"`
	Plan             string             `json:"plan"`
	Action           string             `json:"action"`
	Status           string             `json:"status"`
	Amount           pgtype.Numeric     `json:"amount"`
	Currency         string             `json:"currency"`
	ErrorDescription string             `json:"error_description"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	RefreshHash string             `json:"refresh_hash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	UserAgent   string             `json:"user_agent"`
}

type Transaction struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	CategoryID         pgtype.UUID        `json:"category_id"`
	Amount             pgtype.Numeric     `json:"amount"`
	Currency           string             `json:"currency"`
	Type               string             `json:"type"`
	Date               pgtype.Timestamptz `json:"date"`
	Note               string             `json:"note"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ExternalID         string             `json:"external_id"`
	IsInternalTransfer bool               `json:"is_internal_transfer"`
}

type User struct {
	ID                 pgtype.UUID        `json:"id"`
	AppleSub           pgtype.Text        `json:"apple_sub"`
	Email              pgtype.Text        `json:"email"`
	BaseCurrency       string             `json:"base_currency"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	PasswordHash       pgtype.Text        `json:"password_hash"`
	GoogleSub          pgtype.Text        `json:"google_sub"`
	Theme              string             `json:"theme"`
	GradientColor      string             `json:"gradient_color"`
	Plan               string             `json:"plan"`
	Goals              string             `json:"goals"`
	SubscriptionStatus string             `json:"subscription_status"`
	TrialEndsAt        pgtype.Timestamptz `json:"trial_ends_at"`
	LiqpayOrderID      string             `json:"liqpay_order_id"`
	Name               string             `json:"name"`
	Avatar             string             `json:"avatar"`
}
