// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monobank.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const monobankConnectionDelete = `-- name: MonobankConnectionDelete :exec
DELETE FROM monobank_connections
WHERE user_id = $1
`

func (q *Queries) MonobankConnectionDelete(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, monobankConnectionDelete, userID)
	return err
}

const monobankConnectionGetByUserID = `-- name: MonobankConnectionGetByUserID :one
SELECT user_id, encrypted_token, webhook_secret, masked_pan, account_id, connected_at, last_synced_at
FROM monobank_connections
WHERE user_id = $1
`

func (q *Queries) MonobankConnectionGetByUserID(ctx context.Context, userID pgtype.UUID) (MonobankConnection, error) {
	row := q.db.QueryRow(ctx, monobankConnectionGetByUserID, userID)
	var i MonobankConnection
	err := row.Scan(
		&i.UserID,
		&i.EncryptedToken,
		&i.WebhookSecret,
		&i.MaskedPan,
		&i.AccountID,
		&i.ConnectedAt,
		&i.LastSyncedAt,
	)
	return i, err
}

const monobankConnectionGetByWebhookSecret = `-- name: MonobankConnectionGetByWebhookSecret :one
SELECT user_id, encrypted_token, webhook_secret, masked_pan, account_id, connected_at, last_synced_at
FROM monobank_connections
WHERE webhook_secret = $1
`

func (q *Queries) MonobankConnectionGetByWebhookSecret(ctx context.Context, webhookSecret string) (MonobankConnection, error) {
	row := q.db.QueryRow(ctx, monobankConnectionGetByWebhookSecret, webhookSecret)
	var i MonobankConnection
	err := row.Scan(
		&i.UserID,
		&i.EncryptedToken,
		&i.WebhookSecret,
		&i.MaskedPan,
		&i.AccountID,
		&i.ConnectedAt,
		&i.LastSyncedAt,
	)
	return i, err
}

const monobankConnectionTouchSync = `-- name: MonobankConnectionTouchSync :exec
UPDATE monobank_connections
SET last_synced_at = now()
WHERE user_id = $1
`

func (q *Queries) MonobankConnectionTouchSync(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, monobankConnectionTouchSync, userID)
	return err
}

const monobankConnectionUpsert = `-- name: MonobankConnectionUpsert :one
INSERT INTO monobank_connections (user_id, encrypted_token, webhook_secret, masked_pan, account_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE
SET encrypted_token = EXCLUDED.encrypted_token,
    webhook_secret  = EXCLUDED.webhook_secret,
    masked_pan      = EXCLUDED.masked_pan,
    account_id      = EXCLUDED.account_id,
    connected_at    = now(),
    last_synced_at  = NULL
RETURNING user_id, encrypted_token, webhook_secret, masked_pan, account_id, connected_at, last_synced_at
`

type MonobankConnectionUpsertParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	EncryptedToken []byte      `json:"encrypted_token"`
	WebhookSecret  string      `json:"webhook_secret"`
	MaskedPan      string      `json:"masked_pan"`
	AccountID      string      `json:"account_id"`
}

func (q *Queries) MonobankConnectionUpsert(ctx context.Context, arg MonobankConnectionUpsertParams) (MonobankConnection, error) {
	row := q.db.QueryRow(ctx, monobankConnectionUpsert,
		arg.UserID,
		arg.EncryptedToken,
		arg.WebhookSecret,
		arg.MaskedPan,
		arg.AccountID,
	)
	var i MonobankConnection
	err := row.Scan(
		&i.UserID,
		&i.EncryptedToken,
		&i.WebhookSecret,
		&i.MaskedPan,
		&i.AccountID,
		&i.ConnectedAt,
		&i.LastSyncedAt,
	)
	return i, err
}
