// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const paymentEventCreate = `-- name: PaymentEventCreate :one
INSERT INTO payment_events (user_id, order_id, plan, action, status, amount, currency, error_description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, order_id, plan, action, status, amount, currency, error_description, created_at
`

type PaymentEventCreateParams struct {
	UserID           pgtype.UUID    `json:"user_id"`
	OrderID          string         `json:"order_id"`
	Plan             string         `json:"plan"`
	Action           string         `json:"action"`
	Status           string         `json:"status"`
	Amount           pgtype.Numeric `json:"amount"`
	Currency         string         `json:"currency"`
	ErrorDescription string         `json:"error_description"`
}

func (q *Queries) PaymentEventCreate(ctx context.Context, arg PaymentEventCreateParams) (PaymentEvent, error) {
	row := q.db.QueryRow(ctx, paymentEventCreate,
		arg.UserID,
		arg.OrderID,
		arg.Plan,
		arg.Action,
		arg.Status,
		arg.Amount,
		arg.Currency,
		arg.ErrorDescription,
	)
	var i PaymentEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderID,
		&i.Plan,
		&i.Action,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.ErrorDescription,
		&i.CreatedAt,
	)
	return i, err
}

const paymentEventListForUser = `-- name: PaymentEventListForUser :many
SELECT id, user_id, order_id, plan, action, status, amount, currency, error_description, created_at
FROM payment_events
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type PaymentEventListForUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) PaymentEventListForUser(ctx context.Context, arg PaymentEventListForUserParams) ([]PaymentEvent, error) {
	rows, err := q.db.Query(ctx, paymentEventListForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentEvent
	for rows.Next() {
		var i PaymentEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrderID,
			&i.Plan,
			&i.Action,
			&i.Status,
			&i.Amount,
			&i.Currency,
			&i.ErrorDescription,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
