// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CategoryCreate(ctx context.Context, arg CategoryCreateParams) (Category, error)
	// Only deletes a category owned by the user; default categories can't be deleted this way.
	CategoryDeleteForUser(ctx context.Context, arg CategoryDeleteForUserParams) (int64, error)
	CategoryGetByID(ctx context.Context, id pgtype.UUID) (Category, error)
	// Returns the user's own categories plus the shared default ones.
	CategoryListForUser(ctx context.Context, userID pgtype.UUID) ([]Category, error)
	RateList(ctx context.Context) ([]ExchangeRate, error)
	RateUpsert(ctx context.Context, arg RateUpsertParams) error
	TransactionCreate(ctx context.Context, arg TransactionCreateParams) (Transaction, error)
	TransactionDeleteForUser(ctx context.Context, arg TransactionDeleteForUserParams) (int64, error)
	TransactionListForUser(ctx context.Context, arg TransactionListForUserParams) ([]Transaction, error)
	UserCreate(ctx context.Context, arg UserCreateParams) (User, error)
	UserGetByAppleSub(ctx context.Context, appleSub string) (User, error)
	UserGetByID(ctx context.Context, id pgtype.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
