// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rates.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const rateList = `-- name: RateList :many
SELECT currency, rate_to_uah, updated_at
FROM exchange_rates
ORDER BY currency
`

func (q *Queries) RateList(ctx context.Context) ([]ExchangeRate, error) {
	rows, err := q.db.Query(ctx, rateList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExchangeRate
	for rows.Next() {
		var i ExchangeRate
		if err := rows.Scan(&i.Currency, &i.RateToUah, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rateUpsert = `-- name: RateUpsert :exec
INSERT INTO exchange_rates (currency, rate_to_uah, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (currency) DO UPDATE
SET rate_to_uah = EXCLUDED.rate_to_uah, updated_at = now()
`

type RateUpsertParams struct {
	Currency  string         `json:"currency"`
	RateToUah pgtype.Numeric `json:"rate_to_uah"`
}

func (q *Queries) RateUpsert(ctx context.Context, arg RateUpsertParams) error {
	_, err := q.db.Exec(ctx, rateUpsert, arg.Currency, arg.RateToUah)
	return err
}
