// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const sessionCreate = `-- name: SessionCreate :one
INSERT INTO sessions (user_id, refresh_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, refresh_hash, created_at, expires_at, revoked_at
`

type SessionCreateParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	RefreshHash string             `json:"refresh_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) SessionCreate(ctx context.Context, arg SessionCreateParams) (Session, error) {
	row := q.db.QueryRow(ctx, sessionCreate, arg.UserID, arg.RefreshHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const sessionGetByRefreshHash = `-- name: SessionGetByRefreshHash :one
SELECT id, user_id, refresh_hash, created_at, expires_at, revoked_at
FROM sessions
WHERE refresh_hash = $1
`

func (q *Queries) SessionGetByRefreshHash(ctx context.Context, refreshHash string) (Session, error) {
	row := q.db.QueryRow(ctx, sessionGetByRefreshHash, refreshHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const sessionRevokeByID = `-- name: SessionRevokeByID :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1
`

func (q *Queries) SessionRevokeByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, sessionRevokeByID, id)
	return err
}

const sessionRevokeByRefreshHash = `-- name: SessionRevokeByRefreshHash :exec
UPDATE sessions SET revoked_at = now() WHERE refresh_hash = $1
`

func (q *Queries) SessionRevokeByRefreshHash(ctx context.Context, refreshHash string) error {
	_, err := q.db.Exec(ctx, sessionRevokeByRefreshHash, refreshHash)
	return err
}
