// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const transactionCreate = `-- name: TransactionCreate :one
INSERT INTO transactions (user_id, category_id, amount, currency, type, date, note)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, category_id, amount, currency, type, date, note, created_at
`

type TransactionCreateParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	Amount     pgtype.Numeric     `json:"amount"`
	Currency   string             `json:"currency"`
	Type       string             `json:"type"`
	Date       pgtype.Timestamptz `json:"date"`
	Note       string             `json:"note"`
}

func (q *Queries) TransactionCreate(ctx context.Context, arg TransactionCreateParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, transactionCreate,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Currency,
		arg.Type,
		arg.Date,
		arg.Note,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Currency,
		&i.Type,
		&i.Date,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const transactionDeleteForUser = `-- name: TransactionDeleteForUser :execrows
DELETE FROM transactions
WHERE id = $1 AND user_id = $2
`

type TransactionDeleteForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) TransactionDeleteForUser(ctx context.Context, arg TransactionDeleteForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, transactionDeleteForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const transactionListForUser = `-- name: TransactionListForUser :many
SELECT id, user_id, category_id, amount, currency, type, date, note, created_at
FROM transactions
WHERE user_id = $1
  AND ($2::timestamptz IS NULL OR date >= $2)
  AND ($3::timestamptz IS NULL OR date <= $3)
ORDER BY date DESC
`

type TransactionListForUserParams struct {
	UserID  pgtype.UUID        `json:"user_id"`
	Column2 pgtype.Timestamptz `json:"column_2"`
	Column3 pgtype.Timestamptz `json:"column_3"`
}

func (q *Queries) TransactionListForUser(ctx context.Context, arg TransactionListForUserParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, transactionListForUser, arg.UserID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Currency,
			&i.Type,
			&i.Date,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
