// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const transactionCountForUser = `-- name: TransactionCountForUser :one
SELECT count(*) FROM transactions WHERE user_id = $1
`

func (q *Queries) TransactionCountForUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, transactionCountForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const transactionCreate = `-- name: TransactionCreate :one
INSERT INTO transactions (user_id, category_id, amount, currency, type, date, note)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, category_id, amount, currency, type, date, note, created_at, external_id, is_internal_transfer, operation_amount, operation_currency_code, updated_at
`

type TransactionCreateParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	Amount     pgtype.Numeric     `json:"amount"`
	Currency   string             `json:"currency"`
	Type       string             `json:"type"`
	Date       pgtype.Timestamptz `json:"date"`
	Note       string             `json:"note"`
}

func (q *Queries) TransactionCreate(ctx context.Context, arg TransactionCreateParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, transactionCreate,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Currency,
		arg.Type,
		arg.Date,
		arg.Note,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Currency,
		&i.Type,
		&i.Date,
		&i.Note,
		&i.CreatedAt,
		&i.ExternalID,
		&i.IsInternalTransfer,
		&i.OperationAmount,
		&i.OperationCurrencyCode,
		&i.UpdatedAt,
	)
	return i, err
}

const transactionCreateWithExternalID = `-- name: TransactionCreateWithExternalID :one
INSERT INTO transactions (user_id, category_id, amount, currency, type, date, note, external_id, operation_amount, operation_currency_code)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (user_id, external_id) WHERE external_id <> '' DO NOTHING
RETURNING id, user_id, category_id, amount, currency, type, date, note, created_at, external_id, is_internal_transfer, operation_amount, operation_currency_code, updated_at
`

type TransactionCreateWithExternalIDParams struct {
	UserID                pgtype.UUID        `json:"user_id"`
	CategoryID            pgtype.UUID        `json:"category_id"`
	Amount                pgtype.Numeric     `json:"amount"`
	Currency              string             `json:"currency"`
	Type                  string             `json:"type"`
	Date                  pgtype.Timestamptz `json:"date"`
	Note                  string             `json:"note"`
	ExternalID            string             `json:"external_id"`
	OperationAmount       int64              `json:"operation_amount"`
	OperationCurrencyCode int32              `json:"operation_currency_code"`
}

// Used by Monobank imports (webhook + manual "sync now" backfill) —
// ON CONFLICT DO NOTHING makes re-importing the same statement item a
// harmless no-op instead of a duplicate row. No rows returned means it
// already existed; the caller treats pgx.ErrNoRows as "skipped", not a
// failure. is_internal_transfer always starts false — the account owner
// flags a transfer themselves afterward (see TransactionUpdateForUser),
// automatic detection kept getting confidently wrong. operation_amount/
// operation_currency_code are Monobank's own raw fields (see
// pkg/monobank.StatementItem) — stored durably so a future "what did
// Monobank actually send for this one" question can be answered by
// querying the row directly, without needing a still-live pod's log
// (which a routine redeploy erases) or the user's Monobank token.
func (q *Queries) TransactionCreateWithExternalID(ctx context.Context, arg TransactionCreateWithExternalIDParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, transactionCreateWithExternalID,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Currency,
		arg.Type,
		arg.Date,
		arg.Note,
		arg.ExternalID,
		arg.OperationAmount,
		arg.OperationCurrencyCode,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Currency,
		&i.Type,
		&i.Date,
		&i.Note,
		&i.CreatedAt,
		&i.ExternalID,
		&i.IsInternalTransfer,
		&i.OperationAmount,
		&i.OperationCurrencyCode,
		&i.UpdatedAt,
	)
	return i, err
}

const transactionDeleteExpiredForPlan = `-- name: TransactionDeleteExpiredForPlan :execrows
DELETE FROM transactions
WHERE date < $1
  AND user_id IN (SELECT id FROM users WHERE plan = $2)
`

type TransactionDeleteExpiredForPlanParams struct {
	Date pgtype.Timestamptz `json:"date"`
	Plan string             `json:"plan"`
}

// Data-retention cleanup: Free keeps 30 days, Pro keeps 365 — see
// internal/plan and internal/retention. Max/Enterprise never call this.
func (q *Queries) TransactionDeleteExpiredForPlan(ctx context.Context, arg TransactionDeleteExpiredForPlanParams) (int64, error) {
	result, err := q.db.Exec(ctx, transactionDeleteExpiredForPlan, arg.Date, arg.Plan)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const transactionDeleteForUser = `-- name: TransactionDeleteForUser :execrows
DELETE FROM transactions
WHERE id = $1 AND user_id = $2
`

type TransactionDeleteForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) TransactionDeleteForUser(ctx context.Context, arg TransactionDeleteForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, transactionDeleteForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const transactionListForUser = `-- name: TransactionListForUser :many
SELECT id, user_id, category_id, amount, currency, type, date, note, created_at, external_id, is_internal_transfer, operation_amount, operation_currency_code, updated_at
FROM transactions
WHERE user_id = $1
  AND ($2::timestamptz IS NULL OR date >= $2)
  AND ($3::timestamptz IS NULL OR date <= $3)
ORDER BY date DESC
`

type TransactionListForUserParams struct {
	UserID  pgtype.UUID        `json:"user_id"`
	Column2 pgtype.Timestamptz `json:"column_2"`
	Column3 pgtype.Timestamptz `json:"column_3"`
}

func (q *Queries) TransactionListForUser(ctx context.Context, arg TransactionListForUserParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, transactionListForUser, arg.UserID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Currency,
			&i.Type,
			&i.Date,
			&i.Note,
			&i.CreatedAt,
			&i.ExternalID,
			&i.IsInternalTransfer,
			&i.OperationAmount,
			&i.OperationCurrencyCode,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transactionUpdateForUser = `-- name: TransactionUpdateForUser :one
UPDATE transactions
SET category_id = $3, amount = $4, currency = $5, type = $6, date = $7, note = $8, is_internal_transfer = $9, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, category_id, amount, currency, type, date, note, created_at, external_id, is_internal_transfer, operation_amount, operation_currency_code, updated_at
`

type TransactionUpdateForUserParams struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	CategoryID         pgtype.UUID        `json:"category_id"`
	Amount             pgtype.Numeric     `json:"amount"`
	Currency           string             `json:"currency"`
	Type               string             `json:"type"`
	Date               pgtype.Timestamptz `json:"date"`
	Note               string             `json:"note"`
	IsInternalTransfer bool               `json:"is_internal_transfer"`
}

// updated_at is set here only — never touched by import/create, and
// never used for ORDER BY anywhere (TransactionListForUser sorts by
// `date`, the transaction's own date) — so editing a transaction (e.g.
// fixing its currency) records when the edit happened without ever
// moving the row in the list. is_internal_transfer is user-editable here
// — the account owner's own manual call on whether a transaction is a
// transfer, not a guess this app makes for them.
func (q *Queries) TransactionUpdateForUser(ctx context.Context, arg TransactionUpdateForUserParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, transactionUpdateForUser,
		arg.ID,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Currency,
		arg.Type,
		arg.Date,
		arg.Note,
		arg.IsInternalTransfer,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Currency,
		&i.Type,
		&i.Date,
		&i.Note,
		&i.CreatedAt,
		&i.ExternalID,
		&i.IsInternalTransfer,
		&i.OperationAmount,
		&i.OperationCurrencyCode,
		&i.UpdatedAt,
	)
	return i, err
}
