// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const userCreate = `-- name: UserCreate :one
INSERT INTO users (apple_sub, email, base_currency)
VALUES ($1, $2, $3)
RETURNING id, apple_sub, email, base_currency, created_at
`

type UserCreateParams struct {
	AppleSub     string      `json:"apple_sub"`
	Email        pgtype.Text `json:"email"`
	BaseCurrency string      `json:"base_currency"`
}

func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (User, error) {
	row := q.db.QueryRow(ctx, userCreate, arg.AppleSub, arg.Email, arg.BaseCurrency)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AppleSub,
		&i.Email,
		&i.BaseCurrency,
		&i.CreatedAt,
	)
	return i, err
}

const userGetByAppleSub = `-- name: UserGetByAppleSub :one
SELECT id, apple_sub, email, base_currency, created_at
FROM users
WHERE apple_sub = $1
`

func (q *Queries) UserGetByAppleSub(ctx context.Context, appleSub string) (User, error) {
	row := q.db.QueryRow(ctx, userGetByAppleSub, appleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AppleSub,
		&i.Email,
		&i.BaseCurrency,
		&i.CreatedAt,
	)
	return i, err
}

const userGetByID = `-- name: UserGetByID :one
SELECT id, apple_sub, email, base_currency, created_at
FROM users
WHERE id = $1
`

func (q *Queries) UserGetByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, userGetByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AppleSub,
		&i.Email,
		&i.BaseCurrency,
		&i.CreatedAt,
	)
	return i, err
}
