// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: v1/auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ====================
// SignInWithApple
// ====================
type SignInWithAppleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityToken string                 `protobuf:"bytes,1,opt,name=identity_token,json=identityToken,proto3" json:"identity_token,omitempty"` // Identity token from Sign in with Apple on the device.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInWithAppleRequest) Reset() {
	*x = SignInWithAppleRequest{}
	mi := &file_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInWithAppleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInWithAppleRequest) ProtoMessage() {}

func (x *SignInWithAppleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInWithAppleRequest.ProtoReflect.Descriptor instead.
func (*SignInWithAppleRequest) Descriptor() ([]byte, []int) {
	return file_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *SignInWithAppleRequest) GetIdentityToken() string {
	if x != nil {
		return x.IdentityToken
	}
	return ""
}

type SignInWithAppleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // JWT to use as Bearer token for subsequent calls.
	User          *UserModel_User        `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInWithAppleReply) Reset() {
	*x = SignInWithAppleReply{}
	mi := &file_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInWithAppleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInWithAppleReply) ProtoMessage() {}

func (x *SignInWithAppleReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInWithAppleReply.ProtoReflect.Descriptor instead.
func (*SignInWithAppleReply) Descriptor() ([]byte, []int) {
	return file_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *SignInWithAppleReply) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SignInWithAppleReply) GetUser() *UserModel_User {
	if x != nil {
		return x.User
	}
	return nil
}

// ====================
// DevSignIn
// ====================
type DevSignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // Any stable string identifying the test device/user.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevSignInRequest) Reset() {
	*x = DevSignInRequest{}
	mi := &file_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevSignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevSignInRequest) ProtoMessage() {}

func (x *DevSignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevSignInRequest.ProtoReflect.Descriptor instead.
func (*DevSignInRequest) Descriptor() ([]byte, []int) {
	return file_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *DevSignInRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

var File_v1_auth_proto protoreflect.FileDescriptor

const file_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\rv1/auth.proto\x1a\x1av1/models/model_user.proto\"?\n" +
	"\x16SignInWithAppleRequest\x12%\n" +
	"\x0eidentity_token\x18\x01 \x01(\tR\ridentityToken\"^\n" +
	"\x14SignInWithAppleReply\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\x04user\x18\x02 \x01(\v2\x0f.UserModel.UserR\x04user\"/\n" +
	"\x10DevSignInRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId2\x87\x01\n" +
	"\vAuthService\x12A\n" +
	"\x0fSignInWithApple\x12\x17.SignInWithAppleRequest\x1a\x15.SignInWithAppleReply\x125\n" +
	"\tDevSignIn\x12\x11.DevSignInRequest\x1a\x15.SignInWithAppleReplyB,Z*github.com/rsmrtk/finance-engine/api/v1/pbb\x06proto3"

var (
	file_v1_auth_proto_rawDescOnce sync.Once
	file_v1_auth_proto_rawDescData []byte
)

func file_v1_auth_proto_rawDescGZIP() []byte {
	file_v1_auth_proto_rawDescOnce.Do(func() {
		file_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_auth_proto_rawDesc), len(file_v1_auth_proto_rawDesc)))
	})
	return file_v1_auth_proto_rawDescData
}

var file_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_auth_proto_goTypes = []any{
	(*SignInWithAppleRequest)(nil), // 0: SignInWithAppleRequest
	(*SignInWithAppleReply)(nil),   // 1: SignInWithAppleReply
	(*DevSignInRequest)(nil),       // 2: DevSignInRequest
	(*UserModel_User)(nil),         // 3: UserModel.User
}
var file_v1_auth_proto_depIdxs = []int32{
	3, // 0: SignInWithAppleReply.user:type_name -> UserModel.User
	0, // 1: AuthService.SignInWithApple:input_type -> SignInWithAppleRequest
	2, // 2: AuthService.DevSignIn:input_type -> DevSignInRequest
	1, // 3: AuthService.SignInWithApple:output_type -> SignInWithAppleReply
	1, // 4: AuthService.DevSignIn:output_type -> SignInWithAppleReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_auth_proto_init() }
func file_v1_auth_proto_init() {
	if File_v1_auth_proto != nil {
		return
	}
	file_v1_models_model_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_auth_proto_rawDesc), len(file_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_auth_proto_goTypes,
		DependencyIndexes: file_v1_auth_proto_depIdxs,
		MessageInfos:      file_v1_auth_proto_msgTypes,
	}.Build()
	File_v1_auth_proto = out.File
	file_v1_auth_proto_goTypes = nil
	file_v1_auth_proto_depIdxs = nil
}
