// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: v1/category.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ====================
// CategoryList
// ====================
type CategoryListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListRequest) Reset() {
	*x = CategoryListRequest{}
	mi := &file_v1_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListRequest) ProtoMessage() {}

func (x *CategoryListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListRequest.ProtoReflect.Descriptor instead.
func (*CategoryListRequest) Descriptor() ([]byte, []int) {
	return file_v1_category_proto_rawDescGZIP(), []int{0}
}

type CategoryListReply struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Categories    []*CategoryModel_Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListReply) Reset() {
	*x = CategoryListReply{}
	mi := &file_v1_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListReply) ProtoMessage() {}

func (x *CategoryListReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListReply.ProtoReflect.Descriptor instead.
func (*CategoryListReply) Descriptor() ([]byte, []int) {
	return file_v1_category_proto_rawDescGZIP(), []int{1}
}

func (x *CategoryListReply) GetCategories() []*CategoryModel_Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

// ====================
// CategoryCreate
// ====================
type CategoryCreateRequest struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Name          string                               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IconName      string                               `protobuf:"bytes,2,opt,name=icon_name,json=iconName,proto3" json:"icon_name,omitempty"`
	ColorHex      string                               `protobuf:"bytes,3,opt,name=color_hex,json=colorHex,proto3" json:"color_hex,omitempty"`
	Type          TransactionTypeModel_TransactionType `protobuf:"varint,4,opt,name=type,proto3,enum=TransactionTypeModel_TransactionType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryCreateRequest) Reset() {
	*x = CategoryCreateRequest{}
	mi := &file_v1_category_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryCreateRequest) ProtoMessage() {}

func (x *CategoryCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_category_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryCreateRequest.ProtoReflect.Descriptor instead.
func (*CategoryCreateRequest) Descriptor() ([]byte, []int) {
	return file_v1_category_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryCreateRequest) GetIconName() string {
	if x != nil {
		return x.IconName
	}
	return ""
}

func (x *CategoryCreateRequest) GetColorHex() string {
	if x != nil {
		return x.ColorHex
	}
	return ""
}

func (x *CategoryCreateRequest) GetType() TransactionTypeModel_TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionTypeModel_TRANSACTION_TYPE_UNSPECIFIED
}

type CategoryCreateReply struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Category      *CategoryModel_Category `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryCreateReply) Reset() {
	*x = CategoryCreateReply{}
	mi := &file_v1_category_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryCreateReply) ProtoMessage() {}

func (x *CategoryCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_category_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryCreateReply.ProtoReflect.Descriptor instead.
func (*CategoryCreateReply) Descriptor() ([]byte, []int) {
	return file_v1_category_proto_rawDescGZIP(), []int{3}
}

func (x *CategoryCreateReply) GetCategory() *CategoryModel_Category {
	if x != nil {
		return x.Category
	}
	return nil
}

// ====================
// CategoryDelete
// ====================
type CategoryDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryDeleteRequest) Reset() {
	*x = CategoryDeleteRequest{}
	mi := &file_v1_category_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryDeleteRequest) ProtoMessage() {}

func (x *CategoryDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_category_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryDeleteRequest.ProtoReflect.Descriptor instead.
func (*CategoryDeleteRequest) Descriptor() ([]byte, []int) {
	return file_v1_category_proto_rawDescGZIP(), []int{4}
}

func (x *CategoryDeleteRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

type CategoryDeleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryDeleteReply) Reset() {
	*x = CategoryDeleteReply{}
	mi := &file_v1_category_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryDeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryDeleteReply) ProtoMessage() {}

func (x *CategoryDeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_category_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryDeleteReply.ProtoReflect.Descriptor instead.
func (*CategoryDeleteReply) Descriptor() ([]byte, []int) {
	return file_v1_category_proto_rawDescGZIP(), []int{5}
}

var File_v1_category_proto protoreflect.FileDescriptor

const file_v1_category_proto_rawDesc = "" +
	"\n" +
	"\x11v1/category.proto\x1a\x1ev1/models/model_category.proto\x1a\x1cv1/models/model_common.proto\"\x15\n" +
	"\x13CategoryListRequest\"L\n" +
	"\x11CategoryListReply\x127\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x17.CategoryModel.CategoryR\n" +
	"categories\"\xa0\x01\n" +
	"\x15CategoryCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\ticon_name\x18\x02 \x01(\tR\biconName\x12\x1b\n" +
	"\tcolor_hex\x18\x03 \x01(\tR\bcolorHex\x129\n" +
	"\x04type\x18\x04 \x01(\x0e2%.TransactionTypeModel.TransactionTypeR\x04type\"J\n" +
	"\x13CategoryCreateReply\x123\n" +
	"\bcategory\x18\x01 \x01(\v2\x17.CategoryModel.CategoryR\bcategory\"8\n" +
	"\x15CategoryDeleteRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\"\x15\n" +
	"\x13CategoryDeleteReply2\xcb\x01\n" +
	"\x0fCategoryService\x128\n" +
	"\fCategoryList\x12\x14.CategoryListRequest\x1a\x12.CategoryListReply\x12>\n" +
	"\x0eCategoryCreate\x12\x16.CategoryCreateRequest\x1a\x14.CategoryCreateReply\x12>\n" +
	"\x0eCategoryDelete\x12\x16.CategoryDeleteRequest\x1a\x14.CategoryDeleteReplyB,Z*github.com/rsmrtk/finance-engine/api/v1/pbb\x06proto3"

var (
	file_v1_category_proto_rawDescOnce sync.Once
	file_v1_category_proto_rawDescData []byte
)

func file_v1_category_proto_rawDescGZIP() []byte {
	file_v1_category_proto_rawDescOnce.Do(func() {
		file_v1_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_category_proto_rawDesc), len(file_v1_category_proto_rawDesc)))
	})
	return file_v1_category_proto_rawDescData
}

var file_v1_category_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_category_proto_goTypes = []any{
	(*CategoryListRequest)(nil),               // 0: CategoryListRequest
	(*CategoryListReply)(nil),                 // 1: CategoryListReply
	(*CategoryCreateRequest)(nil),             // 2: CategoryCreateRequest
	(*CategoryCreateReply)(nil),               // 3: CategoryCreateReply
	(*CategoryDeleteRequest)(nil),             // 4: CategoryDeleteRequest
	(*CategoryDeleteReply)(nil),               // 5: CategoryDeleteReply
	(*CategoryModel_Category)(nil),            // 6: CategoryModel.Category
	(TransactionTypeModel_TransactionType)(0), // 7: TransactionTypeModel.TransactionType
}
var file_v1_category_proto_depIdxs = []int32{
	6, // 0: CategoryListReply.categories:type_name -> CategoryModel.Category
	7, // 1: CategoryCreateRequest.type:type_name -> TransactionTypeModel.TransactionType
	6, // 2: CategoryCreateReply.category:type_name -> CategoryModel.Category
	0, // 3: CategoryService.CategoryList:input_type -> CategoryListRequest
	2, // 4: CategoryService.CategoryCreate:input_type -> CategoryCreateRequest
	4, // 5: CategoryService.CategoryDelete:input_type -> CategoryDeleteRequest
	1, // 6: CategoryService.CategoryList:output_type -> CategoryListReply
	3, // 7: CategoryService.CategoryCreate:output_type -> CategoryCreateReply
	5, // 8: CategoryService.CategoryDelete:output_type -> CategoryDeleteReply
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_category_proto_init() }
func file_v1_category_proto_init() {
	if File_v1_category_proto != nil {
		return
	}
	file_v1_models_model_category_proto_init()
	file_v1_models_model_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_category_proto_rawDesc), len(file_v1_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_category_proto_goTypes,
		DependencyIndexes: file_v1_category_proto_depIdxs,
		MessageInfos:      file_v1_category_proto_msgTypes,
	}.Build()
	File_v1_category_proto = out.File
	file_v1_category_proto_goTypes = nil
	file_v1_category_proto_depIdxs = nil
}
