// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: v1/models/model_rate.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RateModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateModel) Reset() {
	*x = RateModel{}
	mi := &file_v1_models_model_rate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateModel) ProtoMessage() {}

func (x *RateModel) ProtoReflect() protoreflect.Message {
	mi := &file_v1_models_model_rate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateModel.ProtoReflect.Descriptor instead.
func (*RateModel) Descriptor() ([]byte, []int) {
	return file_v1_models_model_rate_proto_rawDescGZIP(), []int{0}
}

type RateModel_Rate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      CurrencyModel_Currency `protobuf:"varint,1,opt,name=currency,proto3,enum=CurrencyModel_Currency" json:"currency,omitempty"`
	RateToUah     float64                `protobuf:"fixed64,2,opt,name=rate_to_uah,json=rateToUah,proto3" json:"rate_to_uah,omitempty"` // How many UAH for 1 unit of `currency`.
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`     // RFC3339.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateModel_Rate) Reset() {
	*x = RateModel_Rate{}
	mi := &file_v1_models_model_rate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateModel_Rate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateModel_Rate) ProtoMessage() {}

func (x *RateModel_Rate) ProtoReflect() protoreflect.Message {
	mi := &file_v1_models_model_rate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateModel_Rate.ProtoReflect.Descriptor instead.
func (*RateModel_Rate) Descriptor() ([]byte, []int) {
	return file_v1_models_model_rate_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RateModel_Rate) GetCurrency() CurrencyModel_Currency {
	if x != nil {
		return x.Currency
	}
	return CurrencyModel_CURRENCY_UNSPECIFIED
}

func (x *RateModel_Rate) GetRateToUah() float64 {
	if x != nil {
		return x.RateToUah
	}
	return 0
}

func (x *RateModel_Rate) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_v1_models_model_rate_proto protoreflect.FileDescriptor

const file_v1_models_model_rate_proto_rawDesc = "" +
	"\n" +
	"\x1av1/models/model_rate.proto\x1a\x1cv1/models/model_common.proto\"\x87\x01\n" +
	"\tRateModel\x1az\n" +
	"\x04Rate\x123\n" +
	"\bcurrency\x18\x01 \x01(\x0e2\x17.CurrencyModel.CurrencyR\bcurrency\x12\x1e\n" +
	"\vrate_to_uah\x18\x02 \x01(\x01R\trateToUah\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAtB,Z*github.com/rsmrtk/finance-engine/api/v1/pbb\x06proto3"

var (
	file_v1_models_model_rate_proto_rawDescOnce sync.Once
	file_v1_models_model_rate_proto_rawDescData []byte
)

func file_v1_models_model_rate_proto_rawDescGZIP() []byte {
	file_v1_models_model_rate_proto_rawDescOnce.Do(func() {
		file_v1_models_model_rate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_models_model_rate_proto_rawDesc), len(file_v1_models_model_rate_proto_rawDesc)))
	})
	return file_v1_models_model_rate_proto_rawDescData
}

var file_v1_models_model_rate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_models_model_rate_proto_goTypes = []any{
	(*RateModel)(nil),           // 0: RateModel
	(*RateModel_Rate)(nil),      // 1: RateModel.Rate
	(CurrencyModel_Currency)(0), // 2: CurrencyModel.Currency
}
var file_v1_models_model_rate_proto_depIdxs = []int32{
	2, // 0: RateModel.Rate.currency:type_name -> CurrencyModel.Currency
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_models_model_rate_proto_init() }
func file_v1_models_model_rate_proto_init() {
	if File_v1_models_model_rate_proto != nil {
		return
	}
	file_v1_models_model_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_models_model_rate_proto_rawDesc), len(file_v1_models_model_rate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_models_model_rate_proto_goTypes,
		DependencyIndexes: file_v1_models_model_rate_proto_depIdxs,
		MessageInfos:      file_v1_models_model_rate_proto_msgTypes,
	}.Build()
	File_v1_models_model_rate_proto = out.File
	file_v1_models_model_rate_proto_goTypes = nil
	file_v1_models_model_rate_proto_depIdxs = nil
}
