// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: v1/models/model_user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserModel) Reset() {
	*x = UserModel{}
	mi := &file_v1_models_model_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserModel) ProtoMessage() {}

func (x *UserModel) ProtoReflect() protoreflect.Message {
	mi := &file_v1_models_model_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserModel.ProtoReflect.Descriptor instead.
func (*UserModel) Descriptor() ([]byte, []int) {
	return file_v1_models_model_user_proto_rawDescGZIP(), []int{0}
}

type UserModel_User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	BaseCurrency  CurrencyModel_Currency `protobuf:"varint,3,opt,name=base_currency,json=baseCurrency,proto3,enum=CurrencyModel_Currency" json:"base_currency,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserModel_User) Reset() {
	*x = UserModel_User{}
	mi := &file_v1_models_model_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserModel_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserModel_User) ProtoMessage() {}

func (x *UserModel_User) ProtoReflect() protoreflect.Message {
	mi := &file_v1_models_model_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserModel_User.ProtoReflect.Descriptor instead.
func (*UserModel_User) Descriptor() ([]byte, []int) {
	return file_v1_models_model_user_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UserModel_User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserModel_User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserModel_User) GetBaseCurrency() CurrencyModel_Currency {
	if x != nil {
		return x.BaseCurrency
	}
	return CurrencyModel_CURRENCY_UNSPECIFIED
}

func (x *UserModel_User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_v1_models_model_user_proto protoreflect.FileDescriptor

const file_v1_models_model_user_proto_rawDesc = "" +
	"\n" +
	"\x1av1/models/model_user.proto\x1a\x1cv1/models/model_common.proto\"\x97\x01\n" +
	"\tUserModel\x1a\x89\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12<\n" +
	"\rbase_currency\x18\x03 \x01(\x0e2\x17.CurrencyModel.CurrencyR\fbaseCurrency\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAtB,Z*github.com/rsmrtk/finance-engine/api/v1/pbb\x06proto3"

var (
	file_v1_models_model_user_proto_rawDescOnce sync.Once
	file_v1_models_model_user_proto_rawDescData []byte
)

func file_v1_models_model_user_proto_rawDescGZIP() []byte {
	file_v1_models_model_user_proto_rawDescOnce.Do(func() {
		file_v1_models_model_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_models_model_user_proto_rawDesc), len(file_v1_models_model_user_proto_rawDesc)))
	})
	return file_v1_models_model_user_proto_rawDescData
}

var file_v1_models_model_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_models_model_user_proto_goTypes = []any{
	(*UserModel)(nil),           // 0: UserModel
	(*UserModel_User)(nil),      // 1: UserModel.User
	(CurrencyModel_Currency)(0), // 2: CurrencyModel.Currency
}
var file_v1_models_model_user_proto_depIdxs = []int32{
	2, // 0: UserModel.User.base_currency:type_name -> CurrencyModel.Currency
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_models_model_user_proto_init() }
func file_v1_models_model_user_proto_init() {
	if File_v1_models_model_user_proto != nil {
		return
	}
	file_v1_models_model_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_models_model_user_proto_rawDesc), len(file_v1_models_model_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_models_model_user_proto_goTypes,
		DependencyIndexes: file_v1_models_model_user_proto_depIdxs,
		MessageInfos:      file_v1_models_model_user_proto_msgTypes,
	}.Build()
	File_v1_models_model_user_proto = out.File
	file_v1_models_model_user_proto_goTypes = nil
	file_v1_models_model_user_proto_depIdxs = nil
}
