// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: v1/models/model_transaction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionModel) Reset() {
	*x = TransactionModel{}
	mi := &file_v1_models_model_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionModel) ProtoMessage() {}

func (x *TransactionModel) ProtoReflect() protoreflect.Message {
	mi := &file_v1_models_model_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionModel.ProtoReflect.Descriptor instead.
func (*TransactionModel) Descriptor() ([]byte, []int) {
	return file_v1_models_model_transaction_proto_rawDescGZIP(), []int{0}
}

type TransactionModel_Transaction struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Id            string                               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        string                               `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"` // Decimal as string, e.g. "350.00", to avoid float precision loss.
	Currency      CurrencyModel_Currency               `protobuf:"varint,3,opt,name=currency,proto3,enum=CurrencyModel_Currency" json:"currency,omitempty"`
	Type          TransactionTypeModel_TransactionType `protobuf:"varint,4,opt,name=type,proto3,enum=TransactionTypeModel_TransactionType" json:"type,omitempty"`
	Date          string                               `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"` // RFC3339.
	Note          string                               `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	CategoryId    string                               `protobuf:"bytes,7,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionModel_Transaction) Reset() {
	*x = TransactionModel_Transaction{}
	mi := &file_v1_models_model_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionModel_Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionModel_Transaction) ProtoMessage() {}

func (x *TransactionModel_Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_v1_models_model_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionModel_Transaction.ProtoReflect.Descriptor instead.
func (*TransactionModel_Transaction) Descriptor() ([]byte, []int) {
	return file_v1_models_model_transaction_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TransactionModel_Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransactionModel_Transaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TransactionModel_Transaction) GetCurrency() CurrencyModel_Currency {
	if x != nil {
		return x.Currency
	}
	return CurrencyModel_CURRENCY_UNSPECIFIED
}

func (x *TransactionModel_Transaction) GetType() TransactionTypeModel_TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionTypeModel_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *TransactionModel_Transaction) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TransactionModel_Transaction) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *TransactionModel_Transaction) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

var File_v1_models_model_transaction_proto protoreflect.FileDescriptor

const file_v1_models_model_transaction_proto_rawDesc = "" +
	"\n" +
	"!v1/models/model_transaction.proto\x1a\x1cv1/models/model_common.proto\"\x83\x02\n" +
	"\x10TransactionModel\x1a\xee\x01\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x123\n" +
	"\bcurrency\x18\x03 \x01(\x0e2\x17.CurrencyModel.CurrencyR\bcurrency\x129\n" +
	"\x04type\x18\x04 \x01(\x0e2%.TransactionTypeModel.TransactionTypeR\x04type\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\x12\x1f\n" +
	"\vcategory_id\x18\a \x01(\tR\n" +
	"categoryIdB,Z*github.com/rsmrtk/finance-engine/api/v1/pbb\x06proto3"

var (
	file_v1_models_model_transaction_proto_rawDescOnce sync.Once
	file_v1_models_model_transaction_proto_rawDescData []byte
)

func file_v1_models_model_transaction_proto_rawDescGZIP() []byte {
	file_v1_models_model_transaction_proto_rawDescOnce.Do(func() {
		file_v1_models_model_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_models_model_transaction_proto_rawDesc), len(file_v1_models_model_transaction_proto_rawDesc)))
	})
	return file_v1_models_model_transaction_proto_rawDescData
}

var file_v1_models_model_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_models_model_transaction_proto_goTypes = []any{
	(*TransactionModel)(nil),                  // 0: TransactionModel
	(*TransactionModel_Transaction)(nil),      // 1: TransactionModel.Transaction
	(CurrencyModel_Currency)(0),               // 2: CurrencyModel.Currency
	(TransactionTypeModel_TransactionType)(0), // 3: TransactionTypeModel.TransactionType
}
var file_v1_models_model_transaction_proto_depIdxs = []int32{
	2, // 0: TransactionModel.Transaction.currency:type_name -> CurrencyModel.Currency
	3, // 1: TransactionModel.Transaction.type:type_name -> TransactionTypeModel.TransactionType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_models_model_transaction_proto_init() }
func file_v1_models_model_transaction_proto_init() {
	if File_v1_models_model_transaction_proto != nil {
		return
	}
	file_v1_models_model_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_models_model_transaction_proto_rawDesc), len(file_v1_models_model_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_models_model_transaction_proto_goTypes,
		DependencyIndexes: file_v1_models_model_transaction_proto_depIdxs,
		MessageInfos:      file_v1_models_model_transaction_proto_msgTypes,
	}.Build()
	File_v1_models_model_transaction_proto = out.File
	file_v1_models_model_transaction_proto_goTypes = nil
	file_v1_models_model_transaction_proto_depIdxs = nil
}
