// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: v1/models/model_monobank.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MonobankConnectionModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonobankConnectionModel) Reset() {
	*x = MonobankConnectionModel{}
	mi := &file_v1_models_model_monobank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonobankConnectionModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonobankConnectionModel) ProtoMessage() {}

func (x *MonobankConnectionModel) ProtoReflect() protoreflect.Message {
	mi := &file_v1_models_model_monobank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonobankConnectionModel.ProtoReflect.Descriptor instead.
func (*MonobankConnectionModel) Descriptor() ([]byte, []int) {
	return file_v1_models_model_monobank_proto_rawDescGZIP(), []int{0}
}

type MonobankConnectionModel_Connection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsConnected   bool                   `protobuf:"varint,1,opt,name=is_connected,json=isConnected,proto3" json:"is_connected,omitempty"`
	MaskedPan     string                 `protobuf:"bytes,2,opt,name=masked_pan,json=maskedPan,proto3" json:"masked_pan,omitempty"`            // e.g. "537541******1234", for display only.
	ConnectedAt   string                 `protobuf:"bytes,3,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`      // RFC3339.
	LastSyncedAt  string                 `protobuf:"bytes,4,opt,name=last_synced_at,json=lastSyncedAt,proto3" json:"last_synced_at,omitempty"` // RFC3339, empty if never synced.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonobankConnectionModel_Connection) Reset() {
	*x = MonobankConnectionModel_Connection{}
	mi := &file_v1_models_model_monobank_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonobankConnectionModel_Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonobankConnectionModel_Connection) ProtoMessage() {}

func (x *MonobankConnectionModel_Connection) ProtoReflect() protoreflect.Message {
	mi := &file_v1_models_model_monobank_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonobankConnectionModel_Connection.ProtoReflect.Descriptor instead.
func (*MonobankConnectionModel_Connection) Descriptor() ([]byte, []int) {
	return file_v1_models_model_monobank_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MonobankConnectionModel_Connection) GetIsConnected() bool {
	if x != nil {
		return x.IsConnected
	}
	return false
}

func (x *MonobankConnectionModel_Connection) GetMaskedPan() string {
	if x != nil {
		return x.MaskedPan
	}
	return ""
}

func (x *MonobankConnectionModel_Connection) GetConnectedAt() string {
	if x != nil {
		return x.ConnectedAt
	}
	return ""
}

func (x *MonobankConnectionModel_Connection) GetLastSyncedAt() string {
	if x != nil {
		return x.LastSyncedAt
	}
	return ""
}

var File_v1_models_model_monobank_proto protoreflect.FileDescriptor

const file_v1_models_model_monobank_proto_rawDesc = "" +
	"\n" +
	"\x1ev1/models/model_monobank.proto\"\xb3\x01\n" +
	"\x17MonobankConnectionModel\x1a\x97\x01\n" +
	"\n" +
	"Connection\x12!\n" +
	"\fis_connected\x18\x01 \x01(\bR\visConnected\x12\x1d\n" +
	"\n" +
	"masked_pan\x18\x02 \x01(\tR\tmaskedPan\x12!\n" +
	"\fconnected_at\x18\x03 \x01(\tR\vconnectedAt\x12$\n" +
	"\x0elast_synced_at\x18\x04 \x01(\tR\flastSyncedAtB,Z*github.com/rsmrtk/finance-engine/api/v1/pbb\x06proto3"

var (
	file_v1_models_model_monobank_proto_rawDescOnce sync.Once
	file_v1_models_model_monobank_proto_rawDescData []byte
)

func file_v1_models_model_monobank_proto_rawDescGZIP() []byte {
	file_v1_models_model_monobank_proto_rawDescOnce.Do(func() {
		file_v1_models_model_monobank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_models_model_monobank_proto_rawDesc), len(file_v1_models_model_monobank_proto_rawDesc)))
	})
	return file_v1_models_model_monobank_proto_rawDescData
}

var file_v1_models_model_monobank_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_models_model_monobank_proto_goTypes = []any{
	(*MonobankConnectionModel)(nil),            // 0: MonobankConnectionModel
	(*MonobankConnectionModel_Connection)(nil), // 1: MonobankConnectionModel.Connection
}
var file_v1_models_model_monobank_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_models_model_monobank_proto_init() }
func file_v1_models_model_monobank_proto_init() {
	if File_v1_models_model_monobank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_models_model_monobank_proto_rawDesc), len(file_v1_models_model_monobank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_models_model_monobank_proto_goTypes,
		DependencyIndexes: file_v1_models_model_monobank_proto_depIdxs,
		MessageInfos:      file_v1_models_model_monobank_proto_msgTypes,
	}.Build()
	File_v1_models_model_monobank_proto = out.File
	file_v1_models_model_monobank_proto_goTypes = nil
	file_v1_models_model_monobank_proto_depIdxs = nil
}
