// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: v1/models/model_common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CurrencyModel_Currency int32

const (
	CurrencyModel_CURRENCY_UNSPECIFIED CurrencyModel_Currency = 0
	CurrencyModel_CURRENCY_UAH         CurrencyModel_Currency = 1
	CurrencyModel_CURRENCY_USD         CurrencyModel_Currency = 2
	CurrencyModel_CURRENCY_EUR         CurrencyModel_Currency = 3
	CurrencyModel_CURRENCY_GBP         CurrencyModel_Currency = 4
	CurrencyModel_CURRENCY_PLN         CurrencyModel_Currency = 5
)

// Enum value maps for CurrencyModel_Currency.
var (
	CurrencyModel_Currency_name = map[int32]string{
		0: "CURRENCY_UNSPECIFIED",
		1: "CURRENCY_UAH",
		2: "CURRENCY_USD",
		3: "CURRENCY_EUR",
		4: "CURRENCY_GBP",
		5: "CURRENCY_PLN",
	}
	CurrencyModel_Currency_value = map[string]int32{
		"CURRENCY_UNSPECIFIED": 0,
		"CURRENCY_UAH":         1,
		"CURRENCY_USD":         2,
		"CURRENCY_EUR":         3,
		"CURRENCY_GBP":         4,
		"CURRENCY_PLN":         5,
	}
)

func (x CurrencyModel_Currency) Enum() *CurrencyModel_Currency {
	p := new(CurrencyModel_Currency)
	*p = x
	return p
}

func (x CurrencyModel_Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CurrencyModel_Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_models_model_common_proto_enumTypes[0].Descriptor()
}

func (CurrencyModel_Currency) Type() protoreflect.EnumType {
	return &file_v1_models_model_common_proto_enumTypes[0]
}

func (x CurrencyModel_Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CurrencyModel_Currency.Descriptor instead.
func (CurrencyModel_Currency) EnumDescriptor() ([]byte, []int) {
	return file_v1_models_model_common_proto_rawDescGZIP(), []int{0, 0}
}

type TransactionTypeModel_TransactionType int32

const (
	TransactionTypeModel_TRANSACTION_TYPE_UNSPECIFIED TransactionTypeModel_TransactionType = 0
	TransactionTypeModel_TRANSACTION_TYPE_EXPENSE     TransactionTypeModel_TransactionType = 1
	TransactionTypeModel_TRANSACTION_TYPE_INCOME      TransactionTypeModel_TransactionType = 2
)

// Enum value maps for TransactionTypeModel_TransactionType.
var (
	TransactionTypeModel_TransactionType_name = map[int32]string{
		0: "TRANSACTION_TYPE_UNSPECIFIED",
		1: "TRANSACTION_TYPE_EXPENSE",
		2: "TRANSACTION_TYPE_INCOME",
	}
	TransactionTypeModel_TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_UNSPECIFIED": 0,
		"TRANSACTION_TYPE_EXPENSE":     1,
		"TRANSACTION_TYPE_INCOME":      2,
	}
)

func (x TransactionTypeModel_TransactionType) Enum() *TransactionTypeModel_TransactionType {
	p := new(TransactionTypeModel_TransactionType)
	*p = x
	return p
}

func (x TransactionTypeModel_TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionTypeModel_TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_models_model_common_proto_enumTypes[1].Descriptor()
}

func (TransactionTypeModel_TransactionType) Type() protoreflect.EnumType {
	return &file_v1_models_model_common_proto_enumTypes[1]
}

func (x TransactionTypeModel_TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionTypeModel_TransactionType.Descriptor instead.
func (TransactionTypeModel_TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_v1_models_model_common_proto_rawDescGZIP(), []int{1, 0}
}

type CurrencyModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyModel) Reset() {
	*x = CurrencyModel{}
	mi := &file_v1_models_model_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyModel) ProtoMessage() {}

func (x *CurrencyModel) ProtoReflect() protoreflect.Message {
	mi := &file_v1_models_model_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyModel.ProtoReflect.Descriptor instead.
func (*CurrencyModel) Descriptor() ([]byte, []int) {
	return file_v1_models_model_common_proto_rawDescGZIP(), []int{0}
}

type TransactionTypeModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionTypeModel) Reset() {
	*x = TransactionTypeModel{}
	mi := &file_v1_models_model_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionTypeModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionTypeModel) ProtoMessage() {}

func (x *TransactionTypeModel) ProtoReflect() protoreflect.Message {
	mi := &file_v1_models_model_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionTypeModel.ProtoReflect.Descriptor instead.
func (*TransactionTypeModel) Descriptor() ([]byte, []int) {
	return file_v1_models_model_common_proto_rawDescGZIP(), []int{1}
}

var File_v1_models_model_common_proto protoreflect.FileDescriptor

const file_v1_models_model_common_proto_rawDesc = "" +
	"\n" +
	"\x1cv1/models/model_common.proto\"\x8f\x01\n" +
	"\rCurrencyModel\"~\n" +
	"\bCurrency\x12\x18\n" +
	"\x14CURRENCY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCURRENCY_UAH\x10\x01\x12\x10\n" +
	"\fCURRENCY_USD\x10\x02\x12\x10\n" +
	"\fCURRENCY_EUR\x10\x03\x12\x10\n" +
	"\fCURRENCY_GBP\x10\x04\x12\x10\n" +
	"\fCURRENCY_PLN\x10\x05\"\x86\x01\n" +
	"\x14TransactionTypeModel\"n\n" +
	"\x0fTransactionType\x12 \n" +
	"\x1cTRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TRANSACTION_TYPE_EXPENSE\x10\x01\x12\x1b\n" +
	"\x17TRANSACTION_TYPE_INCOME\x10\x02B,Z*github.com/rsmrtk/finance-engine/api/v1/pbb\x06proto3"

var (
	file_v1_models_model_common_proto_rawDescOnce sync.Once
	file_v1_models_model_common_proto_rawDescData []byte
)

func file_v1_models_model_common_proto_rawDescGZIP() []byte {
	file_v1_models_model_common_proto_rawDescOnce.Do(func() {
		file_v1_models_model_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_models_model_common_proto_rawDesc), len(file_v1_models_model_common_proto_rawDesc)))
	})
	return file_v1_models_model_common_proto_rawDescData
}

var file_v1_models_model_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_models_model_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_models_model_common_proto_goTypes = []any{
	(CurrencyModel_Currency)(0),               // 0: CurrencyModel.Currency
	(TransactionTypeModel_TransactionType)(0), // 1: TransactionTypeModel.TransactionType
	(*CurrencyModel)(nil),                     // 2: CurrencyModel
	(*TransactionTypeModel)(nil),              // 3: TransactionTypeModel
}
var file_v1_models_model_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_models_model_common_proto_init() }
func file_v1_models_model_common_proto_init() {
	if File_v1_models_model_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_models_model_common_proto_rawDesc), len(file_v1_models_model_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_models_model_common_proto_goTypes,
		DependencyIndexes: file_v1_models_model_common_proto_depIdxs,
		EnumInfos:         file_v1_models_model_common_proto_enumTypes,
		MessageInfos:      file_v1_models_model_common_proto_msgTypes,
	}.Build()
	File_v1_models_model_common_proto = out.File
	file_v1_models_model_common_proto_goTypes = nil
	file_v1_models_model_common_proto_depIdxs = nil
}
