// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: v1/models/model_category.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CategoryModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryModel) Reset() {
	*x = CategoryModel{}
	mi := &file_v1_models_model_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryModel) ProtoMessage() {}

func (x *CategoryModel) ProtoReflect() protoreflect.Message {
	mi := &file_v1_models_model_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryModel.ProtoReflect.Descriptor instead.
func (*CategoryModel) Descriptor() ([]byte, []int) {
	return file_v1_models_model_category_proto_rawDescGZIP(), []int{0}
}

type CategoryModel_Category struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Id            string                               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IconName      string                               `protobuf:"bytes,3,opt,name=icon_name,json=iconName,proto3" json:"icon_name,omitempty"`
	ColorHex      string                               `protobuf:"bytes,4,opt,name=color_hex,json=colorHex,proto3" json:"color_hex,omitempty"`
	Type          TransactionTypeModel_TransactionType `protobuf:"varint,5,opt,name=type,proto3,enum=TransactionTypeModel_TransactionType" json:"type,omitempty"`
	IsDefault     bool                                 `protobuf:"varint,6,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryModel_Category) Reset() {
	*x = CategoryModel_Category{}
	mi := &file_v1_models_model_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryModel_Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryModel_Category) ProtoMessage() {}

func (x *CategoryModel_Category) ProtoReflect() protoreflect.Message {
	mi := &file_v1_models_model_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryModel_Category.ProtoReflect.Descriptor instead.
func (*CategoryModel_Category) Descriptor() ([]byte, []int) {
	return file_v1_models_model_category_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CategoryModel_Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CategoryModel_Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryModel_Category) GetIconName() string {
	if x != nil {
		return x.IconName
	}
	return ""
}

func (x *CategoryModel_Category) GetColorHex() string {
	if x != nil {
		return x.ColorHex
	}
	return ""
}

func (x *CategoryModel_Category) GetType() TransactionTypeModel_TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionTypeModel_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *CategoryModel_Category) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

var File_v1_models_model_category_proto protoreflect.FileDescriptor

const file_v1_models_model_category_proto_rawDesc = "" +
	"\n" +
	"\x1ev1/models/model_category.proto\x1a\x1cv1/models/model_common.proto\"\xd4\x01\n" +
	"\rCategoryModel\x1a\xc2\x01\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\ticon_name\x18\x03 \x01(\tR\biconName\x12\x1b\n" +
	"\tcolor_hex\x18\x04 \x01(\tR\bcolorHex\x129\n" +
	"\x04type\x18\x05 \x01(\x0e2%.TransactionTypeModel.TransactionTypeR\x04type\x12\x1d\n" +
	"\n" +
	"is_default\x18\x06 \x01(\bR\tisDefaultB,Z*github.com/rsmrtk/finance-engine/api/v1/pbb\x06proto3"

var (
	file_v1_models_model_category_proto_rawDescOnce sync.Once
	file_v1_models_model_category_proto_rawDescData []byte
)

func file_v1_models_model_category_proto_rawDescGZIP() []byte {
	file_v1_models_model_category_proto_rawDescOnce.Do(func() {
		file_v1_models_model_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_models_model_category_proto_rawDesc), len(file_v1_models_model_category_proto_rawDesc)))
	})
	return file_v1_models_model_category_proto_rawDescData
}

var file_v1_models_model_category_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_models_model_category_proto_goTypes = []any{
	(*CategoryModel)(nil),                     // 0: CategoryModel
	(*CategoryModel_Category)(nil),            // 1: CategoryModel.Category
	(TransactionTypeModel_TransactionType)(0), // 2: TransactionTypeModel.TransactionType
}
var file_v1_models_model_category_proto_depIdxs = []int32{
	2, // 0: CategoryModel.Category.type:type_name -> TransactionTypeModel.TransactionType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_models_model_category_proto_init() }
func file_v1_models_model_category_proto_init() {
	if File_v1_models_model_category_proto != nil {
		return
	}
	file_v1_models_model_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_models_model_category_proto_rawDesc), len(file_v1_models_model_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_models_model_category_proto_goTypes,
		DependencyIndexes: file_v1_models_model_category_proto_depIdxs,
		MessageInfos:      file_v1_models_model_category_proto_msgTypes,
	}.Build()
	File_v1_models_model_category_proto = out.File
	file_v1_models_model_category_proto_goTypes = nil
	file_v1_models_model_category_proto_depIdxs = nil
}
