// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: v1/monobank.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MonobankService_ConnectMonobank_FullMethodName    = "/MonobankService/ConnectMonobank"
	MonobankService_MonobankAccounts_FullMethodName   = "/MonobankService/MonobankAccounts"
	MonobankService_MonobankStatus_FullMethodName     = "/MonobankService/MonobankStatus"
	MonobankService_DisconnectMonobank_FullMethodName = "/MonobankService/DisconnectMonobank"
)

// MonobankServiceClient is the client API for MonobankService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonobankServiceClient interface {
	// ConnectMonobank validates the personal token against Monobank's API,
	// stores it encrypted, and registers our webhook so new transactions get
	// pushed to us automatically.
	ConnectMonobank(ctx context.Context, in *ConnectMonobankRequest, opts ...grpc.CallOption) (*MonobankStatusReply, error)
	MonobankAccounts(ctx context.Context, in *MonobankAccountsRequest, opts ...grpc.CallOption) (*MonobankAccountsReply, error)
	MonobankStatus(ctx context.Context, in *MonobankStatusRequest, opts ...grpc.CallOption) (*MonobankStatusReply, error)
	DisconnectMonobank(ctx context.Context, in *DisconnectMonobankRequest, opts ...grpc.CallOption) (*DisconnectMonobankReply, error)
}

type monobankServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonobankServiceClient(cc grpc.ClientConnInterface) MonobankServiceClient {
	return &monobankServiceClient{cc}
}

func (c *monobankServiceClient) ConnectMonobank(ctx context.Context, in *ConnectMonobankRequest, opts ...grpc.CallOption) (*MonobankStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonobankStatusReply)
	err := c.cc.Invoke(ctx, MonobankService_ConnectMonobank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monobankServiceClient) MonobankAccounts(ctx context.Context, in *MonobankAccountsRequest, opts ...grpc.CallOption) (*MonobankAccountsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonobankAccountsReply)
	err := c.cc.Invoke(ctx, MonobankService_MonobankAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monobankServiceClient) MonobankStatus(ctx context.Context, in *MonobankStatusRequest, opts ...grpc.CallOption) (*MonobankStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonobankStatusReply)
	err := c.cc.Invoke(ctx, MonobankService_MonobankStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monobankServiceClient) DisconnectMonobank(ctx context.Context, in *DisconnectMonobankRequest, opts ...grpc.CallOption) (*DisconnectMonobankReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectMonobankReply)
	err := c.cc.Invoke(ctx, MonobankService_DisconnectMonobank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonobankServiceServer is the server API for MonobankService service.
// All implementations must embed UnimplementedMonobankServiceServer
// for forward compatibility.
type MonobankServiceServer interface {
	// ConnectMonobank validates the personal token against Monobank's API,
	// stores it encrypted, and registers our webhook so new transactions get
	// pushed to us automatically.
	ConnectMonobank(context.Context, *ConnectMonobankRequest) (*MonobankStatusReply, error)
	MonobankAccounts(context.Context, *MonobankAccountsRequest) (*MonobankAccountsReply, error)
	MonobankStatus(context.Context, *MonobankStatusRequest) (*MonobankStatusReply, error)
	DisconnectMonobank(context.Context, *DisconnectMonobankRequest) (*DisconnectMonobankReply, error)
	mustEmbedUnimplementedMonobankServiceServer()
}

// UnimplementedMonobankServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonobankServiceServer struct{}

func (UnimplementedMonobankServiceServer) ConnectMonobank(context.Context, *ConnectMonobankRequest) (*MonobankStatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectMonobank not implemented")
}
func (UnimplementedMonobankServiceServer) MonobankAccounts(context.Context, *MonobankAccountsRequest) (*MonobankAccountsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MonobankAccounts not implemented")
}
func (UnimplementedMonobankServiceServer) MonobankStatus(context.Context, *MonobankStatusRequest) (*MonobankStatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MonobankStatus not implemented")
}
func (UnimplementedMonobankServiceServer) DisconnectMonobank(context.Context, *DisconnectMonobankRequest) (*DisconnectMonobankReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DisconnectMonobank not implemented")
}
func (UnimplementedMonobankServiceServer) mustEmbedUnimplementedMonobankServiceServer() {}
func (UnimplementedMonobankServiceServer) testEmbeddedByValue()                         {}

// UnsafeMonobankServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonobankServiceServer will
// result in compilation errors.
type UnsafeMonobankServiceServer interface {
	mustEmbedUnimplementedMonobankServiceServer()
}

func RegisterMonobankServiceServer(s grpc.ServiceRegistrar, srv MonobankServiceServer) {
	// If the following call panics, it indicates UnimplementedMonobankServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MonobankService_ServiceDesc, srv)
}

func _MonobankService_ConnectMonobank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectMonobankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonobankServiceServer).ConnectMonobank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonobankService_ConnectMonobank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonobankServiceServer).ConnectMonobank(ctx, req.(*ConnectMonobankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonobankService_MonobankAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonobankAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonobankServiceServer).MonobankAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonobankService_MonobankAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonobankServiceServer).MonobankAccounts(ctx, req.(*MonobankAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonobankService_MonobankStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonobankStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonobankServiceServer).MonobankStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonobankService_MonobankStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonobankServiceServer).MonobankStatus(ctx, req.(*MonobankStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonobankService_DisconnectMonobank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectMonobankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonobankServiceServer).DisconnectMonobank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonobankService_DisconnectMonobank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonobankServiceServer).DisconnectMonobank(ctx, req.(*DisconnectMonobankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MonobankService_ServiceDesc is the grpc.ServiceDesc for MonobankService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonobankService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MonobankService",
	HandlerType: (*MonobankServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConnectMonobank",
			Handler:    _MonobankService_ConnectMonobank_Handler,
		},
		{
			MethodName: "MonobankAccounts",
			Handler:    _MonobankService_MonobankAccounts_Handler,
		},
		{
			MethodName: "MonobankStatus",
			Handler:    _MonobankService_MonobankStatus_Handler,
		},
		{
			MethodName: "DisconnectMonobank",
			Handler:    _MonobankService_DisconnectMonobank_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/monobank.proto",
}
