// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: v1/monobank.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ====================
// ConnectMonobank
// ====================
type ConnectMonobankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersonalToken string                 `protobuf:"bytes,1,opt,name=personal_token,json=personalToken,proto3" json:"personal_token,omitempty"` // Generated by the user at https://api.monobank.ua/.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectMonobankRequest) Reset() {
	*x = ConnectMonobankRequest{}
	mi := &file_v1_monobank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectMonobankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectMonobankRequest) ProtoMessage() {}

func (x *ConnectMonobankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_monobank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectMonobankRequest.ProtoReflect.Descriptor instead.
func (*ConnectMonobankRequest) Descriptor() ([]byte, []int) {
	return file_v1_monobank_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectMonobankRequest) GetPersonalToken() string {
	if x != nil {
		return x.PersonalToken
	}
	return ""
}

// ====================
// MonobankStatus
// ====================
type MonobankStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonobankStatusRequest) Reset() {
	*x = MonobankStatusRequest{}
	mi := &file_v1_monobank_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonobankStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonobankStatusRequest) ProtoMessage() {}

func (x *MonobankStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_monobank_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonobankStatusRequest.ProtoReflect.Descriptor instead.
func (*MonobankStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1_monobank_proto_rawDescGZIP(), []int{1}
}

type MonobankStatusReply struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Connection    *MonobankConnectionModel_Connection `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonobankStatusReply) Reset() {
	*x = MonobankStatusReply{}
	mi := &file_v1_monobank_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonobankStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonobankStatusReply) ProtoMessage() {}

func (x *MonobankStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_monobank_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonobankStatusReply.ProtoReflect.Descriptor instead.
func (*MonobankStatusReply) Descriptor() ([]byte, []int) {
	return file_v1_monobank_proto_rawDescGZIP(), []int{2}
}

func (x *MonobankStatusReply) GetConnection() *MonobankConnectionModel_Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

// ====================
// DisconnectMonobank
// ====================
type DisconnectMonobankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectMonobankRequest) Reset() {
	*x = DisconnectMonobankRequest{}
	mi := &file_v1_monobank_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectMonobankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectMonobankRequest) ProtoMessage() {}

func (x *DisconnectMonobankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_monobank_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectMonobankRequest.ProtoReflect.Descriptor instead.
func (*DisconnectMonobankRequest) Descriptor() ([]byte, []int) {
	return file_v1_monobank_proto_rawDescGZIP(), []int{3}
}

type DisconnectMonobankReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectMonobankReply) Reset() {
	*x = DisconnectMonobankReply{}
	mi := &file_v1_monobank_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectMonobankReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectMonobankReply) ProtoMessage() {}

func (x *DisconnectMonobankReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_monobank_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectMonobankReply.ProtoReflect.Descriptor instead.
func (*DisconnectMonobankReply) Descriptor() ([]byte, []int) {
	return file_v1_monobank_proto_rawDescGZIP(), []int{4}
}

var File_v1_monobank_proto protoreflect.FileDescriptor

const file_v1_monobank_proto_rawDesc = "" +
	"\n" +
	"\x11v1/monobank.proto\x1a\x1ev1/models/model_monobank.proto\"?\n" +
	"\x16ConnectMonobankRequest\x12%\n" +
	"\x0epersonal_token\x18\x01 \x01(\tR\rpersonalToken\"\x17\n" +
	"\x15MonobankStatusRequest\"Z\n" +
	"\x13MonobankStatusReply\x12C\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2#.MonobankConnectionModel.ConnectionR\n" +
	"connection\"\x1b\n" +
	"\x19DisconnectMonobankRequest\"\x19\n" +
	"\x17DisconnectMonobankReply2\xdf\x01\n" +
	"\x0fMonobankService\x12@\n" +
	"\x0fConnectMonobank\x12\x17.ConnectMonobankRequest\x1a\x14.MonobankStatusReply\x12>\n" +
	"\x0eMonobankStatus\x12\x16.MonobankStatusRequest\x1a\x14.MonobankStatusReply\x12J\n" +
	"\x12DisconnectMonobank\x12\x1a.DisconnectMonobankRequest\x1a\x18.DisconnectMonobankReplyB,Z*github.com/rsmrtk/finance-engine/api/v1/pbb\x06proto3"

var (
	file_v1_monobank_proto_rawDescOnce sync.Once
	file_v1_monobank_proto_rawDescData []byte
)

func file_v1_monobank_proto_rawDescGZIP() []byte {
	file_v1_monobank_proto_rawDescOnce.Do(func() {
		file_v1_monobank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_monobank_proto_rawDesc), len(file_v1_monobank_proto_rawDesc)))
	})
	return file_v1_monobank_proto_rawDescData
}

var file_v1_monobank_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_monobank_proto_goTypes = []any{
	(*ConnectMonobankRequest)(nil),             // 0: ConnectMonobankRequest
	(*MonobankStatusRequest)(nil),              // 1: MonobankStatusRequest
	(*MonobankStatusReply)(nil),                // 2: MonobankStatusReply
	(*DisconnectMonobankRequest)(nil),          // 3: DisconnectMonobankRequest
	(*DisconnectMonobankReply)(nil),            // 4: DisconnectMonobankReply
	(*MonobankConnectionModel_Connection)(nil), // 5: MonobankConnectionModel.Connection
}
var file_v1_monobank_proto_depIdxs = []int32{
	5, // 0: MonobankStatusReply.connection:type_name -> MonobankConnectionModel.Connection
	0, // 1: MonobankService.ConnectMonobank:input_type -> ConnectMonobankRequest
	1, // 2: MonobankService.MonobankStatus:input_type -> MonobankStatusRequest
	3, // 3: MonobankService.DisconnectMonobank:input_type -> DisconnectMonobankRequest
	2, // 4: MonobankService.ConnectMonobank:output_type -> MonobankStatusReply
	2, // 5: MonobankService.MonobankStatus:output_type -> MonobankStatusReply
	4, // 6: MonobankService.DisconnectMonobank:output_type -> DisconnectMonobankReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_monobank_proto_init() }
func file_v1_monobank_proto_init() {
	if File_v1_monobank_proto != nil {
		return
	}
	file_v1_models_model_monobank_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_monobank_proto_rawDesc), len(file_v1_monobank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_monobank_proto_goTypes,
		DependencyIndexes: file_v1_monobank_proto_depIdxs,
		MessageInfos:      file_v1_monobank_proto_msgTypes,
	}.Build()
	File_v1_monobank_proto = out.File
	file_v1_monobank_proto_goTypes = nil
	file_v1_monobank_proto_depIdxs = nil
}
