// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: v1/rate.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ====================
// RateList
// ====================
type RateListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateListRequest) Reset() {
	*x = RateListRequest{}
	mi := &file_v1_rate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateListRequest) ProtoMessage() {}

func (x *RateListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_rate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateListRequest.ProtoReflect.Descriptor instead.
func (*RateListRequest) Descriptor() ([]byte, []int) {
	return file_v1_rate_proto_rawDescGZIP(), []int{0}
}

type RateListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rates         []*RateModel_Rate      `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateListReply) Reset() {
	*x = RateListReply{}
	mi := &file_v1_rate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateListReply) ProtoMessage() {}

func (x *RateListReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_rate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateListReply.ProtoReflect.Descriptor instead.
func (*RateListReply) Descriptor() ([]byte, []int) {
	return file_v1_rate_proto_rawDescGZIP(), []int{1}
}

func (x *RateListReply) GetRates() []*RateModel_Rate {
	if x != nil {
		return x.Rates
	}
	return nil
}

var File_v1_rate_proto protoreflect.FileDescriptor

const file_v1_rate_proto_rawDesc = "" +
	"\n" +
	"\rv1/rate.proto\x1a\x1av1/models/model_rate.proto\"\x11\n" +
	"\x0fRateListRequest\"6\n" +
	"\rRateListReply\x12%\n" +
	"\x05rates\x18\x01 \x03(\v2\x0f.RateModel.RateR\x05rates2;\n" +
	"\vRateService\x12,\n" +
	"\bRateList\x12\x10.RateListRequest\x1a\x0e.RateListReplyB,Z*github.com/rsmrtk/finance-engine/api/v1/pbb\x06proto3"

var (
	file_v1_rate_proto_rawDescOnce sync.Once
	file_v1_rate_proto_rawDescData []byte
)

func file_v1_rate_proto_rawDescGZIP() []byte {
	file_v1_rate_proto_rawDescOnce.Do(func() {
		file_v1_rate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_rate_proto_rawDesc), len(file_v1_rate_proto_rawDesc)))
	})
	return file_v1_rate_proto_rawDescData
}

var file_v1_rate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_rate_proto_goTypes = []any{
	(*RateListRequest)(nil), // 0: RateListRequest
	(*RateListReply)(nil),   // 1: RateListReply
	(*RateModel_Rate)(nil),  // 2: RateModel.Rate
}
var file_v1_rate_proto_depIdxs = []int32{
	2, // 0: RateListReply.rates:type_name -> RateModel.Rate
	0, // 1: RateService.RateList:input_type -> RateListRequest
	1, // 2: RateService.RateList:output_type -> RateListReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_rate_proto_init() }
func file_v1_rate_proto_init() {
	if File_v1_rate_proto != nil {
		return
	}
	file_v1_models_model_rate_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_rate_proto_rawDesc), len(file_v1_rate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_rate_proto_goTypes,
		DependencyIndexes: file_v1_rate_proto_depIdxs,
		MessageInfos:      file_v1_rate_proto_msgTypes,
	}.Build()
	File_v1_rate_proto = out.File
	file_v1_rate_proto_goTypes = nil
	file_v1_rate_proto_depIdxs = nil
}
