// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: v1/transaction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ====================
// TransactionList
// ====================
type TransactionListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromDate      *string                `protobuf:"bytes,1,opt,name=from_date,json=fromDate,proto3,oneof" json:"from_date,omitempty"` // RFC3339, inclusive.
	ToDate        *string                `protobuf:"bytes,2,opt,name=to_date,json=toDate,proto3,oneof" json:"to_date,omitempty"`       // RFC3339, inclusive.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionListRequest) Reset() {
	*x = TransactionListRequest{}
	mi := &file_v1_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionListRequest) ProtoMessage() {}

func (x *TransactionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionListRequest.ProtoReflect.Descriptor instead.
func (*TransactionListRequest) Descriptor() ([]byte, []int) {
	return file_v1_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionListRequest) GetFromDate() string {
	if x != nil && x.FromDate != nil {
		return *x.FromDate
	}
	return ""
}

func (x *TransactionListRequest) GetToDate() string {
	if x != nil && x.ToDate != nil {
		return *x.ToDate
	}
	return ""
}

type TransactionListReply struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Transactions  []*TransactionModel_Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionListReply) Reset() {
	*x = TransactionListReply{}
	mi := &file_v1_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionListReply) ProtoMessage() {}

func (x *TransactionListReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionListReply.ProtoReflect.Descriptor instead.
func (*TransactionListReply) Descriptor() ([]byte, []int) {
	return file_v1_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionListReply) GetTransactions() []*TransactionModel_Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// ====================
// TransactionCreate
// ====================
type TransactionCreateRequest struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Amount        string                               `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      CurrencyModel_Currency               `protobuf:"varint,2,opt,name=currency,proto3,enum=CurrencyModel_Currency" json:"currency,omitempty"`
	Type          TransactionTypeModel_TransactionType `protobuf:"varint,3,opt,name=type,proto3,enum=TransactionTypeModel_TransactionType" json:"type,omitempty"`
	Date          string                               `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Note          string                               `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	CategoryId    string                               `protobuf:"bytes,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionCreateRequest) Reset() {
	*x = TransactionCreateRequest{}
	mi := &file_v1_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionCreateRequest) ProtoMessage() {}

func (x *TransactionCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionCreateRequest.ProtoReflect.Descriptor instead.
func (*TransactionCreateRequest) Descriptor() ([]byte, []int) {
	return file_v1_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionCreateRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TransactionCreateRequest) GetCurrency() CurrencyModel_Currency {
	if x != nil {
		return x.Currency
	}
	return CurrencyModel_CURRENCY_UNSPECIFIED
}

func (x *TransactionCreateRequest) GetType() TransactionTypeModel_TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionTypeModel_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *TransactionCreateRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TransactionCreateRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *TransactionCreateRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

type TransactionCreateReply struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Transaction   *TransactionModel_Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionCreateReply) Reset() {
	*x = TransactionCreateReply{}
	mi := &file_v1_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionCreateReply) ProtoMessage() {}

func (x *TransactionCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionCreateReply.ProtoReflect.Descriptor instead.
func (*TransactionCreateReply) Descriptor() ([]byte, []int) {
	return file_v1_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionCreateReply) GetTransaction() *TransactionModel_Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// ====================
// TransactionDelete
// ====================
type TransactionDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionDeleteRequest) Reset() {
	*x = TransactionDeleteRequest{}
	mi := &file_v1_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionDeleteRequest) ProtoMessage() {}

func (x *TransactionDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionDeleteRequest.ProtoReflect.Descriptor instead.
func (*TransactionDeleteRequest) Descriptor() ([]byte, []int) {
	return file_v1_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionDeleteRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type TransactionDeleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionDeleteReply) Reset() {
	*x = TransactionDeleteReply{}
	mi := &file_v1_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionDeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionDeleteReply) ProtoMessage() {}

func (x *TransactionDeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionDeleteReply.ProtoReflect.Descriptor instead.
func (*TransactionDeleteReply) Descriptor() ([]byte, []int) {
	return file_v1_transaction_proto_rawDescGZIP(), []int{5}
}

var File_v1_transaction_proto protoreflect.FileDescriptor

const file_v1_transaction_proto_rawDesc = "" +
	"\n" +
	"\x14v1/transaction.proto\x1a!v1/models/model_transaction.proto\x1a\x1cv1/models/model_common.proto\"r\n" +
	"\x16TransactionListRequest\x12 \n" +
	"\tfrom_date\x18\x01 \x01(\tH\x00R\bfromDate\x88\x01\x01\x12\x1c\n" +
	"\ato_date\x18\x02 \x01(\tH\x01R\x06toDate\x88\x01\x01B\f\n" +
	"\n" +
	"_from_dateB\n" +
	"\n" +
	"\b_to_date\"Y\n" +
	"\x14TransactionListReply\x12A\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1d.TransactionModel.TransactionR\ftransactions\"\xeb\x01\n" +
	"\x18TransactionCreateRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\x123\n" +
	"\bcurrency\x18\x02 \x01(\x0e2\x17.CurrencyModel.CurrencyR\bcurrency\x129\n" +
	"\x04type\x18\x03 \x01(\x0e2%.TransactionTypeModel.TransactionTypeR\x04type\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\tR\n" +
	"categoryId\"Y\n" +
	"\x16TransactionCreateReply\x12?\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1d.TransactionModel.TransactionR\vtransaction\"A\n" +
	"\x18TransactionDeleteRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"\x18\n" +
	"\x16TransactionDeleteReply2\xe9\x01\n" +
	"\x12TransactionService\x12A\n" +
	"\x0fTransactionList\x12\x17.TransactionListRequest\x1a\x15.TransactionListReply\x12G\n" +
	"\x11TransactionCreate\x12\x19.TransactionCreateRequest\x1a\x17.TransactionCreateReply\x12G\n" +
	"\x11TransactionDelete\x12\x19.TransactionDeleteRequest\x1a\x17.TransactionDeleteReplyB,Z*github.com/rsmrtk/finance-engine/api/v1/pbb\x06proto3"

var (
	file_v1_transaction_proto_rawDescOnce sync.Once
	file_v1_transaction_proto_rawDescData []byte
)

func file_v1_transaction_proto_rawDescGZIP() []byte {
	file_v1_transaction_proto_rawDescOnce.Do(func() {
		file_v1_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_transaction_proto_rawDesc), len(file_v1_transaction_proto_rawDesc)))
	})
	return file_v1_transaction_proto_rawDescData
}

var file_v1_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_transaction_proto_goTypes = []any{
	(*TransactionListRequest)(nil),            // 0: TransactionListRequest
	(*TransactionListReply)(nil),              // 1: TransactionListReply
	(*TransactionCreateRequest)(nil),          // 2: TransactionCreateRequest
	(*TransactionCreateReply)(nil),            // 3: TransactionCreateReply
	(*TransactionDeleteRequest)(nil),          // 4: TransactionDeleteRequest
	(*TransactionDeleteReply)(nil),            // 5: TransactionDeleteReply
	(*TransactionModel_Transaction)(nil),      // 6: TransactionModel.Transaction
	(CurrencyModel_Currency)(0),               // 7: CurrencyModel.Currency
	(TransactionTypeModel_TransactionType)(0), // 8: TransactionTypeModel.TransactionType
}
var file_v1_transaction_proto_depIdxs = []int32{
	6, // 0: TransactionListReply.transactions:type_name -> TransactionModel.Transaction
	7, // 1: TransactionCreateRequest.currency:type_name -> CurrencyModel.Currency
	8, // 2: TransactionCreateRequest.type:type_name -> TransactionTypeModel.TransactionType
	6, // 3: TransactionCreateReply.transaction:type_name -> TransactionModel.Transaction
	0, // 4: TransactionService.TransactionList:input_type -> TransactionListRequest
	2, // 5: TransactionService.TransactionCreate:input_type -> TransactionCreateRequest
	4, // 6: TransactionService.TransactionDelete:input_type -> TransactionDeleteRequest
	1, // 7: TransactionService.TransactionList:output_type -> TransactionListReply
	3, // 8: TransactionService.TransactionCreate:output_type -> TransactionCreateReply
	5, // 9: TransactionService.TransactionDelete:output_type -> TransactionDeleteReply
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_transaction_proto_init() }
func file_v1_transaction_proto_init() {
	if File_v1_transaction_proto != nil {
		return
	}
	file_v1_models_model_transaction_proto_init()
	file_v1_models_model_common_proto_init()
	file_v1_transaction_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_transaction_proto_rawDesc), len(file_v1_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_transaction_proto_goTypes,
		DependencyIndexes: file_v1_transaction_proto_depIdxs,
		MessageInfos:      file_v1_transaction_proto_msgTypes,
	}.Build()
	File_v1_transaction_proto = out.File
	file_v1_transaction_proto_goTypes = nil
	file_v1_transaction_proto_depIdxs = nil
}
